name: tap_debouncer

packages:
  - '.'
  - '*'
  - '**'

scripts:
  format:
    description: "Format"
    run: |
      dart run melos exec -- dart format .

  analyze:
    description: "Analyze"
    run: |
      dart run melos exec -c 1 -- flutter analyze

  check_format:
    description: "Check format"
    run: |
      dart run melos exec -c 1 -- dart format --set-exit-if-changed .

  test:
    description: "Test"
    run: |
      dart run melos exec -c 1 -- flutter test .

  check:
    description: "Check format, analyze and test"
    run: |
      dart run melos run check_format && \
      dart run melos run analyze && \
      dart run melos run test

  upgrade:
    description: "Upgrade"
    run: |
      dart run melos exec -c 1 -- flutter pub upgrade --major-versions

  fix:
    description: "Fix"
    run: |
      dart pub melos exec -c 1 -- dart fix --apply
