name: tap_debouncer

packages:
  - '.'
  - '*'
  - '**'

scripts:
  format:
    description: "Format"
    run: |
      dart run melos exec --\
        dart format .

  analyze:
    description: "Analyze"
    run: |
      dart run melos exec --concurrency=1 --\
        flutter analyze

  check_format:
    description: "Check format"
    run: |
      dart run melos exec --concurrency=1 --\
        dart format --set-exit-if-changed .

  test:
    description: "Test"
    run: |
      dart run melos exec --concurrency=1 --\
        flutter test --coverage -j 1 .

  check:
    description: "Check format, analyze and test"
    run: |
      dart run melos run check_format && \
      dart run melos run analyze && \
      dart run melos run test && \
      dart run melos run coverage

  upgrade:
    description: "Upgrade"
    run: |
      dart run melos exec --concurrency=1 --\
        flutter pub upgrade --major-versions

  fix:
    description: "Fix"
    run: |
      dart run melos exec --concurrency=1 --\
        dart fix --apply

  coverage:
    description: "Check coverage"
    run: |
      dart pub global activate test_cov_console && \
      result=$(test_cov_console --pass=90) && \
      [ $result == "PASSED" ]
#      lcov --fail-under-lines=90 --summary coverage/lcov.info

