name: tap_debouncer

packages:
  - '.'
  - '*'
  - '**'

scripts:
  format:
    description: "Format"
    run: |
      flutter pub run melos exec -- dart format .

  analyze:
    description: "Analyze"
    run: |
      flutter pub run melos exec -c 1 -- dart analyze

  _format:
    description: "Check format"
    run: |
      flutter pub run melos exec -c 1 -- flutter format -n --set-exit-if-changed .

  test:
    description: "Test"
    run: |
      flutter pub run melos exec -c 1 -- dart test .

  check:
    description: "Check format, analyze and test"
    run: |
      flutter pub run melos run _format && \
      flutter pub run melos run analyze && \
      flutter pub run melos run test

  upgrade:
    description: "Upgrade"
    run: |
      flutter pub run melos exec -c 1 -- flutter pub upgrade --major-versions
